apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
    - port: 80
      targetPort: vproapp-service
      protocol: TCP
  
  selector:
    app: vproapp
  #Type is loadbalancer, it's going to launch an ELB.
  type: LoadBalancer
